ALTER TABLE appointments ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE employees ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE positions ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE supervision_areas ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE competencies ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
